### ISSUE TITLE
not minification/uglification safe?

### ISSUE THREAD

**Issue by kreck** [souly1/ng-walkthrough#10] opened 2015-09-23 15:53 UTC
It seems like the directive is not min/uglify-safe - can anyone confirm?
Potential fixes?

It works fine during development but not after packaging/minification/uglification in my case. I use a modified version of the yeoman generator-angular grunt file.

Regards

**Comment by souly1** [comment] 2015-09-23 18:22
Hey,
I'm using it minified, and I double checked to verify and it indeed is minifying and works fine for me. I'm using a Cordova hook after_prepare using 'uglify-js' and 'clean-css'. What are the symptoms you get?

**Comment by kreck** [comment] 2015-09-24 08:10
![image](https://cloud.githubusercontent.com/assets/4924763/10068376/4005b01c-62a4-11e5-8175-5b1c96950b67.png)
![image](https://cloud.githubusercontent.com/assets/4924763/10068385/592f3568-62a4-11e5-9a51-ec8cb72eadb9.png)
![image](https://cloud.githubusercontent.com/assets/4924763/10068393/68e396a2-62a4-11e5-934e-839209ea0f73.png)
and Lexer errors continue... this only happens when including the directive module as dependency and using it on a screen. I have really no idea where to start investigation...

**Comment by souly1** [comment] 2015-10-11 15:47
Hey @kreck, after @hagai26 's change, get this version and check your issue, tell us if solved (Can't believe I missed it after you opened the issue, I need to check if mine minified correctly...)

**Comment by kreck** [comment] 2015-10-12 10:01
i'll check a.s.a.p. and will report here! Thanks

**Comment by souly1** [comment] 2015-11-04 21:38
Assumed issue closed, Minifies here and no update,
Thanks

**Comment by blackpenny15** [comment] 2016-01-20 08:40
I'm seeing the same issue.

**Comment by blackpenny15** [comment] 2016-01-20 12:39
@souly1 It would seem you have been impugned in this case sir! It's taken some digging, but it seems like what's happening for @kreck and my self is in production we have a basic node script to serve up the index.html from dist,usually a catch all * route, whats happening is when the script requests ng-walkthrough.html, the server is sending the entire index.html back as the response. hopefully that kills this issue.

**Comment by blackpenny15** [comment] 2016-01-20 12:56
var templateUrl = currentScriptPath.replace(new RegExp("ng-walkthrough.js.*"), 'ng-walkthrough.html');

this is the problem line, it presumes the first script is called ng-walkthrough.js, in the case of a yeoman project it will be vendor.js, so the replace fails, and just sucks in what ever script it can get it's hands on, so my previous comment was incorrect

**Comment by souly1** [comment] 2016-01-20 13:21
Hi @blackpenny15, thanks for the input and digging in. Funny how things appear in the same time, @Elpetro just opened an issue which the cause is similar to this (https://github.com/souly1/ng-walkthrough/issues/25) I'll make the change mentioned there embedding the HTML into the directives js and we'll see if the issue is solved.

Thanks

**Comment by souly1** [comment] 2016-01-24 14:11
Hi @blackpenny15 , @kreck , new version has been released, 0.4.1. Can you please update me if the issue has been solved?

Thanks

**Comment by lior-greenblatt** [comment] 2016-01-25 17:29
min/uglify seems to be working for me now

thank you

**Comment by souly1** [comment] 2016-01-27 13:12
Toda Lior,
Closing the issue

**Closed by souly1** 2016-01-27 13:12 UTC
