### ISSUE TITLE
Ionic Material Icons overriding the walkthrough overlay

### ISSUE THREAD

**Issue by Murthy582** [souly1/ng-walkthrough#19] opened 2015-10-16 06:18 UTC
Ionic Material Icons overriding the walkthrough overlay because of z-index. The z-index of ionic material icons is 9999. Please increase the z-index of the walkthrough overlay to make it work with Ionic material.

**Comment by souly1** [comment] 2015-10-16 09:33
Thanks @Murthy582 for the input, I'll look into it when I'll have the time. 
Did you change the z-index of the ng-walkthrouh elements for your App and see it solve the issue?

**Comment by Murthy582** [comment] 2015-10-16 09:46
Yes, I changed the z-index of the walkthrough element and its working as expected.

**Comment by souly1** [comment] 2015-10-16 09:50
Cool, Hopefully update added soon, I'll just have to test it and hopefully add automation tests to work with Ionic Material

**Comment by souly1** [comment] 2015-10-17 16:24
@Murthy582 , I tried out working with Ionic Material, even went through the CSS to find the elements that have the z-index: 9999, added a .button.button-fab but no issues rose,
could you perhaps set a quick plunker example so the issue can be seen?
thanks. 
The control can be seen as round button in image:
![screen shot 2015-10-17 at 7 23 16 pm](https://cloud.githubusercontent.com/assets/6670452/10559962/901c8284-7504-11e5-9433-bcc61bda0482.png)

**Comment by souly1** [comment] 2015-11-04 21:36
closing due to not being able to reproduce

**Closed by souly1** 2015-11-04 21:36 UTC
