### ISSUE TITLE
on-walkthrough-hide is called twice

### ISSUE THREAD

**Issue by hagai26** [souly1/ng-walkthrough#15] opened 2015-10-13 04:15 UTC
one for click event and again for touch event.
Is there any workaround for that?
(Except of ignoring each odd call)

When using ionic serve.

**Comment by souly1** [comment] 2015-10-13 15:08
Hi @hagai26 , I can't reproduce the behaviour on my examples, can you perhaps create a quick demonstration on plunker?

**Comment by hagai26** [comment] 2015-10-14 04:31
Tried with no success. 
In couple of days, I will try uploading my app (which has the bug) after removing the non relevant stuff.

**Comment by souly1** [comment] 2015-10-14 07:59
Cool, I'll take a look when somethings up.

**Comment by souly1** [comment] 2015-11-04 21:37
Anything new? otherwise i'll close this for now since i'm just not able to reproduce

**Comment by hagai26** [comment] 2015-11-05 07:19
Hi,
Tried to use plunker with no success.

I uploaded my example to:
https://github.com/hagai26/ng-walkthrough-ionic-example

**Comment by souly1** [comment] 2015-11-05 12:10
Ok, I'll take a look, Thanks

**Comment by souly1** [comment] 2015-11-11 16:22
I Have a feeling this is connected to Angular/Ionic issue:
https://github.com/angular/angular.js/issues/6251

Together with the 300ms delay most browsers have after tap before click fire I'm introducing to the directive a workaround, ugly for now, with a 500ms timeout until one is allowed another touch event. I think people won't be clicking unless by mistake at a higher rate and then nothing is lost just the touch not registered till touched again. 

For me it solved the issue, tell me your results

**Closed** 2015-11-11 16:24 UTC
Labels: bug

**Comment by hagai26** [comment] 2015-11-11 19:16
Hi,
thanks for fixing this - it worked for me great.

At first, I had a strange behavior but after some debugging I understand different bug which didn't happened before (because the two clicks made it work) - I will open new issue for that.

**Comment by hagai26** [comment] 2015-11-11 19:30
I think it's not actually an issue so I will write it up here:
I'm using onWalkthroughHide to make another walk to show with the following code:
```javascript
$scope.mainCaption = next_caption();
$scope.focusElementId = next_focusElementId();
$scope.isActive = true;
```
This didn't work for me, after some debug came up with this solution:
```javascript
$timeout(function () {
    $scope.mainCaption = next_caption();
    $scope.focusElementId = next_focusElementId();
    $scope.isActive = true;
}, 20);
```

**Comment by souly1** [comment] 2015-11-11 19:43
interesting, won't dig into this now, especially if you solved it, but as the solution involves timeout it could very much be connected to the animation of show hide backdrop (black background).
Great to hear
