### ISSUE TITLE
On hide event not firing

### ISSUE THREAD

**Issue by mkj-git** [souly1/ng-walkthrough#62] opened 2017-01-19 02:09 UTC
I was trying to call a function if i click "Got it" button but event is not getting fired.

```
      <walkthrough
            wid="Demo2"
            walkthrough-type="transparency"
            focus-element-selector="#focus-item"
            icon="arrow"
            main-caption="{{demoCaption2}}"
            icon-padding-left="30"
            icon-padding-top="0"
            force-caption-location="TOP"
            is-active="demoActive2"
            on-walkthrough-hide="next"
            use-button="true">
      </walkthrough>

  $scope.next = function() {
    alert("next called");
  }
```
  
next() is not getting called

**Comment by souly1** [comment] 2017-01-20 20:59
Hi @mkj-git , sorry for the delay.
the walkthrough is over angular 1, so I assume the issue is that you wrote `on-walkthrough-hide="next"`instead of `on-walkthrough-hide="next()"`
Tell me if this solved the issue.
Thanks

**Comment by souly1** [comment] 2017-01-26 14:51
Closing due to lack of responsiveness

**Closed by souly1** 2017-01-26 14:51 UTC
